# Generated by Django 2.2.24 on 2024-06-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcommunitycomment',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newcommunitycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newforum.NewCommunityPost'),
        ),
        migrations.AlterField(
            model_name='newcommunitypost',
            name='createdBy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
