# Generated by Django 2.2.24 on 2025-08-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedtask',
            name='description',
        ),
    ]
