# Generated by Django 2.2.24 on 2025-09-01 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250830_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sharedtask',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
