# Generated by Django 4.2.25 on 2025-10-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20251006_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenfija',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenfija/'),
        ),
        migrations.AlterField(
            model_name='imagenfija',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_fijas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
