# Generated by Django 2.2.24 on 2026-01-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagenfija_image_alter_imagenfija_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
