# Generated by Django 2.1.7 on 2021-06-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_communitycomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.CommunityComment'),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.CommunityPost'),
        ),
    ]
